export const START_LOADING = 'START_LOADINg'
export const END_LOADING = 'END_LOADING'

// appSystem
export const FETCH_APP_SYSTEM = 'FETCH_APP_SYSTEM'
export const FETCH_PLATFORM_SYSTEM = 'FETCH_PLATFORM_SYSTEM'
export const FETCH_PROJECTS = 'FETCH_PROJECTS'

//menus
export const FETCH_MENUS = 'FETCH_MENUS'


//roles
export const FETCH_ROLES = 'FETCH_ROLES'
export const CREATE_ROLES = 'CREATE_ROLES'
export const GET_ROLES_BY_ID = 'GET_ROLES_BY_ID'
export const UPDATE_ROLES_BY_ID = 'UPDATE_ROLES_BY_ID'
export const UPDATEROLE_BY_ID = 'UPDATEROLE_BY_ID'

//users
export const GET_PERSON_INFO = 'GET_PERSON_INFO'
export const GET_USER_TABLE = 'GET_USER_TABLE'
export const GET_USER_BY_USERNAME = 'GET_USER_BY_USERNAME'
export const GET_ROLEAUTHS_BY_USERNAME = 'GET_ROLEAUTHS_BY_USERNAME'
export const UPDATE_USER = 'UPDATE_USER'

//dict

export const GET_DICTTYPE_TABLE = 'GET_DICTTYPE_TABLE'
export const GET_DICTTYPE_BY_ID = 'GET_DICTTYPE_BY_ID'
export const GET_UNDER_DICTTYPE = 'GET_UNDER_DICTTYPE'
export const GET_DICT_BY_ID = 'GET_DICT_BY_ID'
export const DELETE_DICTTYPE_BY_IDS = 'DELETE_DICTTYPE_BY_IDS'


//workgroup
export const GET_WORKGROUP_LIST = 'GET_WORKGROUP_LIST'
export const GET_WORKGROUP_INFO_BY_ID = 'GET_WORKGROUP_INFO_BY_ID'
export const GET_EMPLOYEES_INFO_BY_ID = 'GET_EMPLOYEES_INFO_BY_ID'
export const GET_ASSOCIATED_ACCOUNT = 'GET_ASSOCIATED_ACCOUNT'
export const GET_ORG_TREE = 'GET_ORG_TREE'
export const GET_ORGINFO_BY_ID = 'GET_ORGINFO_BY_ID'
export const GET_POSITIONINFO_BY_ID = 'GET_POSITIONINFO_BY_ID'
export const GET_EMPLOYEE_UNDER_ORG = 'GET_EMPLOYEE_UNDER_ORG'
export const GET_EMPLOYEE_UNDER_POSITION = 'GET_EMPLOYEE_UNDER_POSITION'
export const GET_ORG_LIST = 'GET_ORG_LIST'
export const CREATE_USER_OK = 'CREATE_USER_OK'
export const GET_EMPLOYEE_LIST = 'GET_EMPLOYEE_LIST'
export const GET_EMPLOYEE_ASS_LIST = 'GET_EMPLOYEE_ASS_LIST'

//app
export const GET_APP_LIST = 'GET_APP_LIST'
export const GET_APPINFO_BY_ID = 'GET_APPINFO_BY_ID'